[components.pipewire]
# Release: %[%{baserelease} + %{azl_release}]%{?snapdate:.%{snapdate}git%{shortcommit}}%{?dist}
release = { calculation = "static", counter = { source = "spec-macro", directive = "global", name = "azl_release" } }
build.without = ["v4l2", "roc"]
