[components.kdump-anaconda-addon]
# Release: 16.%{snapshotdate}git%{gitshortcommit}%{?dist}
release = { calculation = "static", counter = { source = "release-tag", regex = '^([0-9]+)\.%\{snapshotdate\}git%\{gitshortcommit\}%\{\?dist\}$' } }
