[components.csnappy]
# Release: 32.20211216git%{shortcommit}%{?dist}
release = { calculation = "static", counter = { source = "release-tag", regex = '^([0-9]+)\.[0-9]+git%\{shortcommit\}%\{\?dist\}$' } }
