[components.glusterfs]
# Release: 0.@PACKAGE_RELEASE@%{?dist}.26
release = { calculation = "static", counter = { source = "release-tag", regex = '^([0-9]+)%\{\?prereltag:%\{prereltag\}\}%\{\?dist\}$' } }
