[components.pulseaudio]
# Release: %[9 + %{azl_release}]%{?snap:.%{snap}git%{shortcommit}}%{?dist}
release = { calculation = "static", counter = { source = "spec-macro", directive = "global", name = "azl_release" } }
